import cabinet, \
CreateCompressor, 'CreateCompressor', \
SetCompressorInformation, 'SetCompressorInformation', \
QueryCompressorInformation, 'QueryCompressorInformation', \
Compress, 'Compress', \
ResetCompressor, 'ResetCompressor', \
CloseCompressor, 'CloseCompressor', \
CreateDecompressor, 'CreateDecompressor', \
SetDecompressorInformation, 'SetDecompressorInformation', \
QueryDecompressorInformation, 'QueryDecompressorInformation', \
Decompress, 'Decompress', \
ResetDecompressor, 'ResetDecompressor', \
CloseDecompressor, 'CloseDecompressor'